### ISSUE TITLE
Version Tags

### ISSUE THREAD

**Issue by brodkin** [aegypius/docker-confd#1]
Would it be possible to get tags for the confd versions? Apparently there is some drama, as discussed at kelseyhightower/confd#195, in which etcd v0.4.6 is no longer compatible with the current version of confd now that it has been updated to to support etcd v2. Even a docker tag for 0.4.6-compat would be a lifesaver at the moment.

**Comment by aegypius** [comment]
Thanks for the report. I don't really know how tags works with Docker Hub Trusted Builds, but I'll try to do that.

**Comment by aegypius** [comment]
@brodkin I tried to generate a tag from this repository but I am unable to push a tag when an automated build is setup. Maybe the best option is to provide an _official_ confd container directly from
kelseyhightower/confd instead of using my method. Feel free to open an issue on kelseyhightower/confd I will happily help to setup things.

For the record, I no longer use confd, this repository has been kept for documentation.
